# Generated by Django 4.0.2 on 2022-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrefer',
            name='userCode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrefer',
            name='userCodeInitials',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrefer',
            name='userCodeNumber',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
